#!/usr/bin/env bash

set -e

function busybox-pv-cleanup() {
    $SUDO xl destroy raisin-test || true
    umount $LOOP || true
    cd "$BASEDIR"
    $SUDO losetup -d $LOOP
    rm -rf $TMPDIR
}

function busybox-pv-test() {
    TMPDIR=`mktemp -d`
    cd $TMPDIR
    
    allocate_disk busybox-vm-disk $((20*1024*1024))
    LOOP=`create_loop busybox-vm-disk`
    busybox_rootfs $LOOP
    busybox_network_init $LOOP
    
    cat >busybox-pv <<EOF
kernel = "`get_host_kernel`"
ramdisk = "`get_host_initrd`"
extra = "root=/dev/xvda console=hvc0"
memory = 512
name = "raisin-test"
vcpus = 2
disk = [ '$LOOP,raw,xvda,w' ]
serial="pty"
boot="c"
vif=['bridge=xenbr1']
EOF
    
    $SUDO xl create busybox-pv
    check_guest_alive
}
