#!/usr/bin/env bash

set -e

source "$BASEDIR"/tests/busybox-hvm

function busybox-hvm-migrate-cleanup() {
    rm -f $TMPSCRIPT
    busybox-hvm-cleanup
}

function busybox-hvm-migrate-test() {
    if [[ $RAISIN_ARCH != "x86_64" && $RAISIN_ARCH != "x86_32" ]]
    then
        echo $PREPEND busybox hvm test only valid on x86
        exit 0
    fi

    busybox-hvm-test

    TMPSCRIPT=`mktemp`

    cat >$TMPSCRIPT <<EOF
#!/usr/bin/env bash

shift
\$*
EOF

    chmod +x $TMPSCRIPT
    xl migrate -s $TMPSCRIPT raisin-test localhost
    check_guest_alive
}
