#!/usr/bin/env bash

function ovmf_skip() {
    case $RAISIN_ARCH in
        "x86_32" )
            verbose_echo "Building OVMF for x86_64 guests"
            return 1
            ;;
        "arm32" )
            return 0
            ;;
        "arm64"|"x86_64" )
            return 1
            ;;
    esac
}

function ovmf_check_package() {
    local DEP_Debian_common="build-essential uuid-dev python iasl"
    local DEP_Debian_x86_32="$DEP_Debian_common nasm"
    local DEP_Debian_x86_64="$DEP_Debian_x86_32"
    local DEP_Debian_arm64="$DEP_Debian_common"

    local DEP_Fedora_common="make gcc gcc-c++ libuuid-devel python acpica-tools"
    local DEP_Fedora_x86_32="$DEP_Fedora_common nasm"
    local DEP_Fedora_x86_64="$DEP_Fedora_x86_32"
    local DEP_Fedora_arm64="$DEP_Fedora_common"

    local DEP_CentOS_common="$DEP_Fedora_common"
    local DEP_CentOS_x86_32="$DEP_Fedora_x86_32"
    local DEP_CentOS_x86_64="$DEP_Fedora_x86_64"
    local DEP_CentOS_arm64="$DEP_Fedora_arm64"

    verbose_echo Checking OVMF dependencies
    eval check-package \$DEP_"$DISTRO"_"$RAISIN_ARCH"
}


function ovmf_build() {
    cd "$BASEDIR"
    git-checkout $OVMF_URL $OVMF_REVISION ovmf-dir
    cd ovmf-dir

    make -C BaseTools

    if [[ $RAISIN_ARCH = "arm64" ]]
    then
        # Just use gcc4.8 flags for now: we have to specify a gcc
        # version and the 4.8 flags are almost identical to 4.9, etc.
        # As a consequence we are always going to use the large model.
        bash -c "source edksetup.sh && \
                 build -a AARCH64 -t GCC48 -p ArmVirtPkg/ArmVirtXen.dsc -b RELEASE"
        mkdir -p "$INST_DIR"/$PREFIX/lib/xen/boot
        cp Build/ArmVirtXen-AARCH64/RELEASE_GCC*/FV/XEN_EFI.fd "$INST_DIR"/$PREFIX/lib/xen/boot/XEN_EFI.fd
    else
        OvmfPkg/build.sh -a X64 -b RELEASE -n 4
        cp Build/OvmfX64/RELEASE_GCC*/FV/OVMF.fd ovmf.bin
    fi

    cd "$BASEDIR"
}

function ovmf_clean() {
    cd "$BASEDIR"
    if [[ -d ovmf-dir ]]
    then
        cd ovmf-dir
        $GIT clean -fdx
        cd ..
        rm -rf ovmf-dir
    fi
}

function ovmf_configure() {
    :
}

function ovmf_unconfigure() {
    :
}
