#!/usr/bin/env bash

function qemu_traditional_check_package() {
    local DEP_Debian_common="build-essential zlib1g-dev pciutils-dev pkg-config \
              libncurses5-dev"
    local DEP_Debian_x86_32="$DEP_Debian_common"
    local DEP_Debian_x86_64="$DEP_Debian_common"

    local DEP_Fedora_common="make gcc zlib-devel ncurses-devel pciutils-devel"
    local DEP_Fedora_x86_32="$DEP_Fedora_common"
    local DEP_Fedora_x86_64="$DEP_Fedora_common"

    if [[ $RAISIN_ARCH != "x86_64" && $RAISIN_ARCH != "x86_32" ]]
    then
        verbose_echo qemu_traditional is only supported on x86_32 and x86_64
        return
    fi

    verbose_echo Checking QEMU dependencies
    eval check-package \$DEP_"$DISTRO"_"$RAISIN_ARCH"
}

function qemu_traditional_build() {
    if [[ $RAISIN_ARCH != "x86_64" && $RAISIN_ARCH != "x86_32" ]]
    then
        verbose_echo qemu_traditional is only supported on x86_32 and x86_64
        return
    fi

    cd "$BASEDIR"
    git-checkout $QEMU_TRADITIONAL_URL $QEMU_TRADITIONAL_REVISION qemu_traditional-dir
    cd qemu_traditional-dir

    export CONFIG_BLKTAP1=n
    export XEN_ROOT="$BASEDIR"/xen-dir
    ./xen-setup
    $RAISIN_MAKE all
    $RAISIN_MAKE install DESTDIR="$INST_DIR"
    cd "$BASEDIR"
}

function qemu_traditional_clean() {
    cd "$BASEDIR"
    if [[ -d qemu_traditional-dir ]]
    then
        cd qemu_traditional-dir
        $MAKE distclean
        cd ..
        rm -rf qemu_traditional-dir
    fi
}

function qemu_traditional_configure() {
    :
}

function qemu_traditional_unconfigure() {
    :
}
