#!/usr/bin/env bash

function qemu_skip() {
    return 1
}

function qemu_check_package() {
    local DEP_Debian_common="build-essential libglib2.0-dev libpixman-1-dev"
    local DEP_Debian_x86_32="$DEP_Debian_common"
    local DEP_Debian_x86_64="$DEP_Debian_common"
    local DEP_Debian_arm32="$DEP_Debian_common"
    local DEP_Debian_arm64="$DEP_Debian_common"

    local DEP_Fedora_common="make gcc glib2-devel pixman-devel zlib-devel"
    local DEP_Fedora_x86_32="$DEP_Fedora_common"
    local DEP_Fedora_x86_64="$DEP_Fedora_common"

    verbose_echo Checking QEMU dependencies
    eval check-package \$DEP_"$DISTRO"_"$RAISIN_ARCH"
}

function qemu_build() {
    cd "$BASEDIR"
    git-checkout $QEMU_URL $QEMU_REVISION qemu-dir
    cd qemu-dir
    ./configure --enable-xen --target-list=i386-softmmu --prefix=$PREFIX \
        --extra-cflags="-I$INST_DIR/$PREFIX/include" \
        --extra-ldflags="-L$INST_DIR/$PREFIX/lib -Wl,-rpath-link=$INST_DIR/$PREFIX/lib \
                         -L$INST_DIR/$PREFIX/lib64 -Wl,-rpath-link=$INST_DIR/$PREFIX/lib64" \
        --disable-kvm \
        --disable-docs \
        --bindir=$PREFIX/lib/xen/bin \
        --datadir=$PREFIX/share/qemu-xen \
        --disable-guest-agent
    $RAISIN_MAKE all
    $RAISIN_MAKE install DESTDIR="$INST_DIR"
    cd "$BASEDIR"
}

function qemu_clean() {
    cd "$BASEDIR"
    if [[ -d qemu-dir ]]
    then
        cd qemu-dir
        $RAISIN_MAKE distclean
        cd ..
        rm -rf qemu-dir
    fi
}

function qemu_configure() {
    :
}

function qemu_unconfigure() {
    :
}
