#!/usr/bin/env bash
#
# mkdeb: package $INST_DIR output in a .deb
#
# Takes 1 argument: the package name
# It relies on RAISIN_ARCH and INST_DIR being set correctly

set -e

if [[ -z "$1" ]]
then
    echo "usage: $0 package_name"
    exit 1
fi

name=$1

cd "$BASEDIR"

# map the architecture, if necessary
case "$RAISIN_ARCH" in
    x86_32|x86_32p)  arch=i386 ;;
    x86_64)  arch=amd64 ;;
    arm32)   arch=armhf ;;
    arm64)   arch=$RAISIN_ARCH;;
    *) echo "Unknown ARCH $RAISIN_ARCH" >&2
       exit 1
       ;;
esac

# Prepare the directory to package
rm -rf deb
cp -a "$INST_DIR" deb
mkdir -p deb/opt/raisin
cp -r data deb/opt/raisin
cp -r components deb/opt/raisin
cp -r scripts deb/opt/raisin
cp -r lib deb/opt/raisin
cp config raise deb/opt/raisin


# Debian doesn't use /usr/lib64 for 64-bit libraries
if [[ -d deb/usr/lib64 ]]
then
    cp -a deb/usr/lib64/* deb/usr/lib/
    rm -rf deb/usr/lib64
fi

# Fill in the debian boilerplate
mkdir -p deb/DEBIAN
cat >deb/DEBIAN/control <<EOF
Package: $name
Source: raisin
Version: $(date +"%Y%m%d.%H%M%S")
Architecture: $arch
Maintainer: Unmaintained snapshot
Section: admin
Priority: optional
Installed-Size: $(du -ks deb | cut -f1)
Description: Raisin build
 Warning: This is a custom build of Xen, Libvirt and other
 components; it is not an  officially supported Debian package.
 It is just the output of a raish.sh wrapped in a .deb
 to make it easy to update and uninstall.
EOF
# Find all /etc files and add them to conffiles
find deb/etc -type f -printf /etc/%P\\n >deb/DEBIAN/conffiles


# Package it up
chown -R root:root deb
dpkg --build deb $name.deb

# Tidy up after ourselves
rm -rf deb
